name: Publish module

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  publish:
    name: Publish module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Publish
        env:
          API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path . -NuGetApiKey $env:API_KEY -Verbose
