name: Release, tag, and publish

on:
  push:
    paths:
      - "**/*.ps1"
      - "**/*.psm1"
      - "**/*.psd1"
      - "Public/**"
      - "Private/**"
    branches:
      - 'main'

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  tag-and-release:
    name: Tag and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          ref: 'main'

      - name: release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = 'Stop'
          $manifestPath = (Get-ChildItem -Path . -Filter "*.psd1").FullName
          $manifestData = Test-ModuleManifest -Path $manifestPath
          if ($manifestData.Version.Build -ne 0) {
            Write-Output "Not a major or minor version update"
            exit
          }
          git fetch --all
          $tag = "v" + $manifestData.Version.ToString()
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@not-a-real-email.org"
          git tag $tag
          git push origin $tag
          Start-Sleep -Seconds 2
          gh release create $tag --verify-tag --fail-on-no-commits

  publish:
    name: Publish module
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          ref: 'main'

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish.yml --ref main
