name: Release module

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          ref: 'main'

      - name: release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = 'Stop'
          git fetch --all
          $tag = $(git describe --tags --exact-match).trim()
          $tagVersion = $tag.Substring(1, $tag.Length - 1)
          $manifestPath = (Get-ChildItem -Path . -Filter "*.psd1").FullName
          $module = Test-ModuleManifest -Path $manifestPath
          $modVersion = $module.version.ToString()
          Write-Output "Tag version is $tagVersion, manifest version is $modVersion"
          if ($tagVersion -eq $modVersion) {
            gh release create $tag --verify-tag --fail-on-no-commits
          }
          else {
            throw "Tag version does not match module manifest version"
          }

  publish:
    name: Publish module
    needs: [release]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          ref: 'main'

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish.yml --ref main
