name: Run Pester tests

on:
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
    branches:
      - 'main'

permissions:
  checks: write
  contents: read

jobs:
  tests:
    name: Run Pester tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Run tests
        shell: pwsh
        run: |
          Install-Module Pester -SkipPublisherCheck -Force
          pwsh ./Tests/RunTests.ps1
